<?php

namespace App\Controllers;
use App\Controllers\BaseController;
use App\Models\pagosModel;
use App\Models\prestamoModel;
//use App\Models\pagosModel;
use CodeIgniter\RESTful\ResourceController;

class prestamos extends ResourceController{
    protected $modelName= 'App\Models\prestamoModel';
    protected $format= 'json';

    public function index(){
        return $this->gResponse($this->model->findAll(), "",200);
    }
    public function show($id = null){
        $presta= $this->model->find($id);
        if($presta){
            return $this->gResponse($presta,"",200);
        }else{
            return $this->gResponse("","Eror",500);
        }
      // return parent::show($id); // TODO: Change the autogenerated stub
    }

    public function create(){
        $prestamo = new prestamoModel();
        $pagos = new pagosModel();

        $id = $prestamo->insert([
            'monto'=>$this->request->getPost('monto'),
            'tasa'=>$this->request->getPost('tasa'),
            'plazo'=>$this->request->getPost('plazo'),
            'fecha'=>date('Y-m-d h:i:s')
        ]);
        return $this->gResponse($this->model->find($id), "", 200);
        //return parent::create(); // TODO: Change the autogenerated stub
    }

    private function gResponse($data, $mensaje, $code){
        if($code==200){
            return $this->respond(array(
                'data'=>$data,
                'code'=>$code
            ));
        }else{
            return $this->respond(array(
                'msj'=>$mensaje,
                'code'=>$code
            ));
        }
    }
}